=== Butterfly-Junction-Technologies/wzdx/sample-files/xml-schema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>WZDx Road Events Feed</xs:documentation>
	</xs:annotation>
  
  <!-- ********************************************************************* -->
  <!-- Feed Root Element -->
  <!-- ********************************************************************* -->
	<xs:element name="wzdx_road_events_feed">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="road_event_feed_info" type="RoadEventFeedInfo"/>
				<xs:element name="road_events" type="RoadEvents"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
  
  <!-- ********************************************************************* -->
  <!-- Complex Type Definitions -->
  <!-- ********************************************************************* -->
  <xs:complexType name="RoadEventFeedInfo">
    <xs:sequence>
      <xs:element name="feed_info_id" type="xs:string"/>
      <xs:element name="feed_update_date" type="xs:dateTime"/>
      <xs:element name="metadata" type="xs:string" minOccurs="0"/>
      <xs:element name="version" type="xs:decimal" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="RoadEvents">
    <xs:sequence>
      <xs:element name="road_event" type="RoadEvent" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  
	<xs:complexType name="RoadEvent">
		<xs:sequence>
			<xs:element name="road_event_id" type="xs:string"/>
			<xs:element name="subidentifier" type="xs:string" maxOccurs="0"/>
			<xs:element name="geometry_type" type="GeometryType"/>
			<xs:element name="geometry" type="xs:string"/>
			<xs:element name="road_name" type="xs:string"/>
			<xs:element name="road_number" type="xs:string" maxOccurs="0"/>
			<xs:element name="direction" type="Direction"/>
			<xs:element name="beginning_cross_street" type="xs:string" maxOccurs="0"/>
			<xs:element name="ending_cross_street" type="xs:string" maxOccurs="0"/>
			<xs:element name="beginning_milepost" type="xs:string" maxOccurs="0"/>
			<xs:element name="ending_milepost" type="xs:string" maxOccurs="0"/>
			<xs:element name="beginning_accuracy" type="Accuracy"/>
			<xs:element name="ending_accuracy" type="Accuracy"/>
			<xs:element name="start_date" type="xs:dateTime"/>
			<xs:element name="end_date" type="xs:dateTime"/>
			<xs:element name="start_date_accuracy" type="Accuracy"/>
			<xs:element name="end_date_accuracy" type="Accuracy"/>
			<xs:element name="event_status" type="EventStatus" maxOccurs="0"/>
			<xs:element name="total_num_lanes" type="xs:integer" minOccurs="0"/>
			<xs:element name="open_lanes" type="LaneType" minOccurs="0"/>
			<xs:element name="closed_lanes" type="LaneType"/>
			<xs:element name="closed_shoulders" type="ClosedShouldersType" minOccurs="0"/>
			<xs:element name="workers_present" type="xs:boolean" minOccurs="0"/>
			<xs:element name="reduced_speed_limit" type="xs:integer" minOccurs="0"/>
			<xs:element name="restrictions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="restriction" type="Restriction" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
			<xs:element name="description" type="xs:string" minOccurs="0"/>
			<xs:element name="issuing_organization" type="xs:string" minOccurs="0"/>
			<xs:element name="creation_date" type="xs:dateTime" minOccurs="0"/>
			<xs:element name="update_date" type="xs:dateTime" minOccurs="0"/>							
		</xs:sequence>
	</xs:complexType>
	
  <!-- ********************************************************************* -->
	<!-- Enumerated Type Definitions -->
  <!-- ********************************************************************* -->
  <xs:simpleType name="GeometryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MultiPoint"/>
      <xs:enumeration value="LineString"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- from TMDD Link-alignment -->
	<xs:simpleType name="Direction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="northbound"/>
			<xs:enumeration value="southbound"/>
			<xs:enumeration value="eastbound"/>
			<xs:enumeration value="westbound"/>
		</xs:restriction>
	</xs:simpleType>
  
  <xs:simpleType name="Accuracy">
    <xs:restriction base="xs:string">
      <xs:enumeration value="estimated"/>
      <xs:enumeration value="verified"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="EventStatus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="planned"/>
      <xs:enumeration value="pending"/>
      <xs:enumeration value="active"/>
      <xs:enumeration value="cancelled"/>
      <xs:enumeration value="completed"/>
    </xs:restriction>
  </xs:simpleType>

	<!-- from ITIS.LaneRoadways -->
	<xs:simpleType name="LaneType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="all"/>
			<xs:enumeration value="left-lane"/>
			<xs:enumeration value="right-lane"/>
			<xs:enumeration value="left-2-lanes"/>
			<xs:enumeration value="left-3-lanes"/>
			<xs:enumeration value="right-2-lanes"/>
			<xs:enumeration value="right-3-lanes"/>
			<xs:enumeration value="center"/>
			<xs:enumeration value="middle-lane"/>
			<xs:enumeration value="right-turning-lane"/>
			<xs:enumeration value="left-turning-lane"/>
			<xs:enumeration value="right-exit-lane"/>
			<xs:enumeration value="left-exit-lane"/>
			<xs:enumeration value="right-merging-lane"/>
			<xs:enumeration value="left-merging-lane"/>
			<xs:enumeration value="right-exit-ramp"/>
			<xs:enumeration value="right-second-exit-ramp"/>
			<xs:enumeration value="right-entrance-ramp"/>
			<xs:enumeration value="right-second-entrance-ramp"/>	
			<xs:enumeration value="left-exit-ramp"/>
			<xs:enumeration value="left-second-exit-ramp"/>
			<xs:enumeration value="left-entrance-ramp"/>
			<xs:enumeration value="left-second-entrance-ramp"/>
			<xs:enumeration value="sidewalk"/>
			<xs:enumeration value="bike-lane"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="unknown"/>
			<xs:enumeration value="alternating-flow-lane"/>
			<xs:enumeration value="shift-left"/>
			<xs:enumeration value="shift-right"/>
		</xs:restriction>
	</xs:simpleType>
  
	<xs:simpleType name="ClosedShouldersType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="outside"/>
			<xs:enumeration value="inside"/>
			<xs:enumeration value="both"/>
			<xs:enumeration value="none"/>
			<xs:enumeration value="unknown"/>
		</xs:restriction>
	</xs:simpleType>
  
  <xs:simpleType name="Restriction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="no-trucks"/>
      <xs:enumeration value="travel-peak-hours-only"/>
      <xs:enumeration value="hov-3"/>
      <xs:enumeration value="hov-2"/>
      <xs:enumeration value="no-parking"/>
      <xs:enumeration value="bike-lane"/>
      <xs:enumeration value="reduced-width"/>
      <xs:enumeration value="reduced-height"/>
      <xs:enumeration value="reduced-length"/>
      <xs:enumeration value="axle-load-limit"/>
      <xs:enumeration value="gross-weight-limit"/>
      <xs:enumeration value="towing-prohibited"/>
      <xs:enumeration value="permitted-oversize-loads-prohibited"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== Butterfly-Junction-Technologies/wzdx/sample-files/sample-feed.xml
<?xml version="1.0" encoding="UTF-8"?>
<wzdx_road_events_feed xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xml-schema.xsd">
	<road_event_feed_info>
		<feed_info_id>ID</feed_info_id>
		<feed_update_date>2016-04-12T00:01:00</feed_update_date>
		<metadata>URL</metadata>
		<version>2.0</version>
	</road_event_feed_info>
  <road_events>
    <road_event>
  		<road_event_id>ID</road_event_id>
  		<feed_info_id>ID</feed_info_id>
  		<subidentifier>ID</event_subidentifier>
  		<geometry_type>MultiPoint</geometry_type>
  		<geometry>[[40.635122,-122.733841],[40.67201,-122.654384]]</geometry>
  		<road_name>Text</road_name>
  		<road_number>Text</road_number>
  		<direction>eastbound</direction>
  		<beginning_cross_street>Text</beginning_cross_street>
  		<ending_cross_street>Text</ending_cross_street>
  		<beginning_milepost>1.5</beginning_milepost>
  		<ending_milepost>2.5</ending_milepost>
  		<beginning_accuracy>estimated</beginning_accuracy>
  		<ending_accuracy>estimated</ending_accuracy>
  		<start_date>2016-11-03T19:37:00</start_date>
  		<end_date>2016-11-04T05:30:00</end_date>
  		<start_date_accuracy>estimated</start_date_accuracy>
  		<end_date_accuracy>estimated</end_date_accuracy>
  		<event_status>planned</event_status>
  		<total_num_lanes>2</total_num_lanes>
  		<open_lanes>right-lane</open_lanes>
  		<closed_lanes>left-lane</closed_lanes>
  		<closed_shoulders>inside</closed_shoulders>
  		<workers_present>true</workers_present>
  		<reduced_speed_limit>20</reduced_speed_limit>
  		<restrictions>
        <restriction>no-trucks</restriction>
      </restrictions>
  		<description>Text</description>
  		<issuing_organization>Text</issuing_organization>
  		<creation_date>2016-04-12T00:01:00</creation_date>
  		<update_date>2016-04-12T00:01:00</update_date>
  	</road_event>
  </road_events>
</WZDx>
